# fly.toml app configuration file generated for 415-project-snowy-lake-8192 on 2025-03-14T09:13:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '415-project-snowy-lake-8192'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
